---
apiVersion: apps/v1 
Kind: Deployment
metadata:
  name: {{ .Values.metadata.name  }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template: {{ .Values.template | toYaml | nindent 4 }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports: {{ .Values.ports | toYaml | nindent 11 }}