apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
replicas: 2 
template:
  metadata:
    labels:
      app: qt
name: firstplace
image:
  name: "nginx"
  tag: "1.27"
ports:
  - containerPort: 80
      
---
apiVersion: v1
Kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: qt
ports:
  - port: 80
    targetPort: 80
    protocol: TCP      